module.exports = {
  home: [
    'home/home',
    {
      type: 'category',
      label: 'Mobile Network',
      link: { type: 'doc', id: 'network-mobile/5g-on-helium' },
      items: [
        {
          type: 'category',
          label: 'Convert WiFi Networks',
          collapsed: false,
          link: { type: 'doc', id: 'network-mobile/data-only-mobile' },
          items: [
            {
              type: 'doc',
              id: 'network-mobile/data-only-mobile',
              label: 'Introduction',
            },
            'network-mobile/data-only-guides/data-only-onboarding',
            'network-mobile/data-only-guides/data-only-radsecproxy',
            'network-mobile/data-only-guides/data-only-aruba',
            'network-mobile/data-only-guides/data-only-fortinet',
            'network-mobile/data-only-guides/data-only-juniper-mist',
            'network-mobile/data-only-guides/data-only-meraki',
            'network-mobile/data-only-guides/data-only-mikrotik',
            'network-mobile/data-only-guides/data-only-ruckus',
            'network-mobile/data-only-guides/data-only-ubiquiti',
            'network-mobile/data-only-guides/data-only-generic',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'IoT Network',
      link: { type: 'doc', id: 'network-iot/lorawan-network-servers/lorawan-network-servers' },
      items: [
        'network-iot/lorawan-network-servers/find-a-lns-provider',
        {
          type: 'category',
          label: 'Run Your Own LNS',
          link: { type: 'doc', id: 'network-iot/run-an-lns/run-an-lns' },
          items: [
            'network-iot/run-an-lns/buy-an-oui',
            {
              type: 'category',
              label: 'Fund an Organizationally Unique Identifier',
              link: { type: 'doc', id: 'network-iot/run-an-lns/fund-an-oui' },
              items: ['tokens/data-credit-portal', 'network-iot/run-an-lns/fund-an-oui-using-hnt'],
            },
            {
              type: 'category',
              label: 'Configure ChirpStack',
              link: { type: 'doc', id: 'network-iot/run-an-lns/configure-chirpstack' },
              items: ['network-iot/run-an-lns/docker-compose', 'network-iot/run-an-lns/kubernetes'],
            },
            'network-iot/run-an-lns/configure-routing-rules',
            'network-iot/run-an-lns/chirpstack-add-device',
            'network-iot/run-an-lns/chirpstack-add-device-grpc',
            'network-iot/run-an-lns/advanced-configuration',
            'network-iot/run-an-lns/common-issues',
          ],
        },
        'network-iot/lorawan-roaming',

        {
          type: 'category',
          label: 'Data-Only Hotspots',
          link: { type: 'doc', id: 'network-iot/hotspots-iot/data-only-hotspots' },
          items: [
            'network-iot/hotspots-iot/data-only-hotspots',
            'network-iot/hotspots-iot/data-only-hotspots-onboarding',
            'network-iot/hotspots-iot/data-only/balena-data-only-hotspot',
            'network-iot/hotspots-iot/data-only/dragino-data-only-hotspot',
            'network-iot/hotspots-iot/data-only/rak-concentrators',
          ],
        },
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Tokens',
      link: { type: 'doc', id: 'tokens/hnt-token' },
      items: ['tokens/hnt-token', 'tokens/data-credit', 'tokens/sol-token'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Wallets',
      link: { type: 'doc', id: 'wallets/wallets' },
      items: [
        'wallets/wallets',
        'wallets/helium-wallet-app',
        'wallets/third-party-wallets',
        'wallets/wallet-seed-phrase',
        'wallets/ledger-wallet',
        'wallets/cli-wallet',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Network Data',
      link: { type: 'doc', id: 'network-data/network-data' },
      items: [
        {
          type: 'category',
          label: 'API Providers',
          link: { type: 'doc', id: 'network-data/api-providers' },
          items: ['network-data/entity-api'],
        },
        'network-data/oracle-data',
        'network-data/legacy-blockchain-data',
      ],
      collapsed: true,
    },
  ],
}
