module.exports = {
  home: [
    {
      type: 'category',
      label: 'Home',
      link: { type: 'doc', id: 'home/home' },
      items: ['home/about-helium', 'home/helium-history'],
    },
    {
      type: 'category',
      label: 'FAQ',
      link: { type: 'doc', id: 'faq/helium-network' },
      items: [
        'faq/security',
        'faq/open-source',
        'faq/docs-installation',
        'faq/privacy',
        'faq/terms',
      ],
      collapsed: true,
    },
  ],

  architecture: [
    {
      type: 'category',
      label: 'Solana',
      link: { type: 'doc', id: 'solana/solana' },
      items: ['solana/primer', 'solana/rewardable-entities', 'solana/compression-nfts'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Oracles',
      link: { type: 'doc', id: 'oracles/oracles' },
      items: [
        'oracles/data-transfer-oracles',
        'oracles/iot-proof-of-coverage-oracles',
        'oracles/mobile-proof-of-coverage-oracles',
        'oracles/oracle-data',
        'oracles/price-oracles',
        'oracles/rewards-oracles',
      ],
      collapsed: true,
    },

    {
      type: 'category',
      label: 'Hotspots',
      link: { type: 'doc', id: 'hotspot-makers/become-a-maker/basic-miner-operation' },
      items: [
        {
          type: 'category',
          label: 'IOT Hotspots',
          link: { type: 'doc', id: 'hotspot-makers/iot/light-hotspots' },
          items: [
            'hotspot-makers/become-a-maker/docker-integration',
            'hotspot-makers/become-a-maker/hotspot-ble-services',
            'hotspot-makers/become-a-maker/hotspot-wifi-configuration',
            'hotspot-makers/become-a-maker/maker-app-requirements',
            'hotspot-makers/become-a-maker/security-requirements',
          ],
        },
        {
          type: 'category',
          label: 'Data Only Hotspots',
          link: { type: 'doc', id: 'hotspot-makers/iot/data-only-hotspots' },
          items: [
            'hotspot-makers/iot/data-only/balena-data-only-hotspot',
            'hotspot-makers/iot/data-only/dragino-pg1301',
            'hotspot-makers/iot/data-only/dragino',
            'hotspot-makers/iot/data-only/kerlink',
            'hotspot-makers/iot/data-only/rak-concentrators',
          ],
        },
        'hotspot-makers/mobile-cbrs/5g-hardware-specification',
        {
          type: 'category',
          label: 'Hotspot Makers',
          link: { type: 'doc', id: 'hotspot-makers/hotspot-makers' },
          items: [
            'hotspot-makers/mcc/compliance-committee',
            'hotspot-makers/mcc/maker-ethics',
            'hotspot-makers/become-a-maker/burn-hnt-to-maker-wallet',
            'hotspot-makers/become-a-maker/funding-a-maker-account',
          ],
          collapsed: true,
        },
        {
          type: 'category',
          label: 'Audit Process',
          link: { type: 'doc', id: 'hotspot-makers/mcc/hotspot-audit-process' },
          items: [
            'hotspot-makers/become-a-maker/maker-approval-auditing',
            'hotspot-makers/mcc/fcc-compliance',
            'hotspot-makers/mcc/ce-red-compliance',
            'hotspot-makers/become-a-maker/hotspot-integration-testing',
          ],
        },
      ],
      collapsed: true,
    },
  ],

  tokens: [
    'helium-tokens/hnt-token',
    'helium-tokens/iot-token',
    'helium-tokens/mobile-token',
    {
      type: 'category',
      label: 'Data Credit Tokens',
      link: { type: 'doc', id: 'helium-tokens/data-credit' },
      items: ['helium-tokens/data-credit', 'helium-tokens/data-credit-portal'],
      collapsed: true,
    },
    'helium-tokens/sol-token',
  ],

  wallets: [
    'wallets/wallets',
    'wallets/helium-wallet-app',
    'wallets/wallet-seed-phrase',
    'wallets/ledger',
    'wallets/cli-wallet',
  ],

  iot_network: [
    {
      type: 'category',
      label: 'Use the Helium IoT Network',
      link: { type: 'doc', id: 'use-the-network/use-the-network' },
      items: [],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Devices',
      link: { type: 'doc', id: 'use-the-network/devices/devices' },
      items: [
        'use-the-network/devices/ready-to-use/ready-to-use',
        'use-the-network/devices/development/development',
      ],
    },
    {
      type: 'category',
      label: 'LoRaWAN Network Servers',
      link: { type: 'doc', id: 'use-the-network/lorawan-network-servers' },
      items: [
        'network-iot/open-lns',
        'use-the-network/find-a-lns-provider',
        'network-iot/open-lns-quickstart',
        'use-the-network/run-a-network-server/buy-an-oui',
      ],
    },
    {
      type: 'category',
      label: 'LoRaWAN on Helium',
      link: { type: 'doc', id: 'network-iot/lorawan-on-helium' },
      items: [
        'network-iot/frequency-plans/frequency-plans',
        'network-iot/frequency-plans/region-plans',
        {
          type: 'category',
          label: 'Roaming',
          link: { type: 'doc', id: 'network-iot/lorawan-roaming' },
          items: ['network-iot/lorawan-roaming-quickstart', 'use-the-network/roaming'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Proof of Coverage',
      link: { type: 'doc', id: 'blockchain/proof-of-coverage' },
      items: [
        'network-iot/iot-poc',
        {
          type: 'category',
          label: 'Coverage Mapping',
          link: { type: 'doc', id: 'network-iot/coverage-mapping/coverage-mapping' },
          items: [
            'network-iot/coverage-mapping/mappers-api',
            'network-iot/coverage-mapping/mappers-roadmap',
          ],
        },
      ],
    },
  ],

  mobile_network: [
    {
      type: 'category',
      label: '5G on Helium',
      link: { type: 'doc', id: 'network-mobile/cbrs/5g-on-helium' },
      items: [
        'network-mobile/cbrs/cbrs-radios',
        'network-mobile/mobile-mappers',
        'network-mobile/mobile-poc',
        'network-mobile/service-providers',
      ],
      collapsed: true,
    },
  ],

  governance: [
    'governance/governance',
    'governance/voting',
    'governance/faq',
    'governance/realms',
    'vote-escrow/vehnt',
    'vote-escrow/realms',
    'governance/working-groups',
    'governance/committees',
    {
      type: 'category',
      label: 'Improvement Proposals',
      link: { type: 'doc', id: 'governance/hip' },
      items: ['faq/write-a-hip', 'faq/edit-a-hip'],
    },
  ],

  archive: [
    {
      type: 'category',
      label: 'Blockchain',
      link: { type: 'doc', id: 'blockchain/blockchain' },
      items: [
        'blockchain/blockchain-primitives',
        'blockchain/mining',
        'blockchain/transaction-fees',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Mine IOT',
      link: { type: 'doc', id: 'helium-tokens/mine-iot' },
      items: [
        'network-iot/crowdspot',
        'network-iot/denylist',
        'network-iot/denylist-removals',
        'faq/build-on-network',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'API',
      link: { type: 'doc', id: 'api/home' },
      items: [
        {
          type: 'category',
          label: 'Blockchain API',
          link: { type: 'doc', id: 'api/blockchain/introduction' },
          items: [
            'api/blockchain/stats',
            'api/blockchain/blocks',
            'api/blockchain/accounts',
            'api/blockchain/hotspots',
            'api/blockchain/cities',
            'api/blockchain/locations',
            'api/blockchain/transactions',
            'api/blockchain/pending-transactions',
            'api/blockchain/oracle-prices',
            'api/blockchain/chain-variables',
            'api/blockchain/ouis',
            'api/blockchain/rewards',
            'api/blockchain/dc-burns',
            'api/blockchain/challenges',
            'api/blockchain/elections',
            'api/blockchain/state-channels',
            'api/blockchain/assert-locations',
            'api/blockchain/validators',
          ],
          collapsed: true,
        },
        'api/console',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Console',
      link: { type: 'doc', id: 'use-the-network/console/quickstart' },
      items: [
        'use-the-network/console/users',
        'use-the-network/console/adding-devices',
        {
          type: 'category',
          label: 'Migrating Devices',
          link: {
            type: 'doc',
            id: 'use-the-network/console/migrating-devices/migrating-devices',
          },
          items: [
            'use-the-network/console/migrating-devices/ttn-import',
            'use-the-network/console/migrating-devices/ttn-manual',
          ],
          collapsed: true,
        },
        'use-the-network/console/labels',
        'use-the-network/console/debug',
        'use-the-network/console/alerts',
        'use-the-network/console/multi-packets',
        'use-the-network/console/profiles',
        {
          type: 'category',
          label: 'Flows',
          link: { type: 'doc', id: 'use-the-network/console/flows/flows' },
          items: [
            'use-the-network/console/flows/orientation',
            'use-the-network/console/flows/actions',
            'use-the-network/console/flows/flows-faq',
          ],
          collapsed: true,
        },
        'use-the-network/console/functions',
        {
          type: 'category',
          label: 'Integrations',
          link: { type: 'doc', id: 'use-the-network/console/integrations/integrations' },
          items: [
            'use-the-network/console/integrations/json-schema',
            'use-the-network/console/integrations/http',
            'use-the-network/console/integrations/mqtt',
            'use-the-network/console/integrations/azure',
            'use-the-network/console/integrations/aws-iot-core',
            'use-the-network/console/integrations/cargo',
            'use-the-network/console/integrations/datacake',
            'use-the-network/console/integrations/mydevices-cayenne',
            'use-the-network/console/integrations/adafruitio',
            'use-the-network/console/integrations/ubidots',
            'use-the-network/console/integrations/tago',
            'use-the-network/console/integrations/google-sheets',
            'use-the-network/console/integrations/microshare',
            'use-the-network/console/integrations/akenza',
          ],
          collapsed: true,
        },
        'use-the-network/console/coverage',
        'use-the-network/console/console-cli',
        'use-the-network/console/console-api',
        'use-the-network/console/my-account',
        'use-the-network/console/troubleshooting',
        'use-the-network/console/hosting-providers',
        'use-the-network/run-a-network-server/run-a-network-server',
        'blockchain/packet-purchasing',
      ],
      collapsed: true,
    },
  ],

  iot_device_ready_to_use: [
    {
      type: 'link',
      label: '<- Devices',
      href: '/use-the-network/devices',
    },
    'use-the-network/devices/ready-to-use/ready-to-use',
    {
      type: 'category',
      label: 'Abeeway',
      items: [
        'use-the-network/devices/ready-to-use/abeeway/abeeway-geolocation-module',
        'use-the-network/devices/ready-to-use/abeeway/abeeway-industrial-tracker',
        'use-the-network/devices/ready-to-use/abeeway/abeeway-compact-tracker',
        'use-the-network/devices/ready-to-use/abeeway/abeeway-micro-tracker',
        'use-the-network/devices/ready-to-use/abeeway/abeeway-smart-badge',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Adeunis',
      items: ['use-the-network/devices/ready-to-use/adeunis/adeunis-field-test-device'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Acqua-Scope',
      items: [
        'use-the-network/devices/ready-to-use/aquascope/bvs',
        'use-the-network/devices/ready-to-use/aquascope/wwd',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Beiselen',
      items: ['use-the-network/devices/ready-to-use/beiselen/radar'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'BoatOfficer',
      items: ['use-the-network/devices/ready-to-use/boatofficer/boatofficerblue'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Bosch',
      items: ['use-the-network/devices/ready-to-use/bosch/tps110'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Comtac',
      items: [
        'use-the-network/devices/ready-to-use/comtac/lpn-td1',
        'use-the-network/devices/ready-to-use/comtac/cluey-km',
        'use-the-network/devices/ready-to-use/comtac/lpn-tsm',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Decent Lab',
      items: [
        'use-the-network/devices/ready-to-use/decentlab/dl-iam',
        'use-the-network/devices/ready-to-use/decentlab/dl-pr26',
        'use-the-network/devices/ready-to-use/decentlab/dl-mbx',
        'use-the-network/devices/ready-to-use/decentlab/dl-5tm',
        'use-the-network/devices/ready-to-use/decentlab/dl-atm22',
        'use-the-network/devices/ready-to-use/decentlab/dl-atm41',
        'use-the-network/devices/ready-to-use/decentlab/dl-ctd10',
        'use-the-network/devices/ready-to-use/decentlab/dl-dlr2-002',
        'use-the-network/devices/ready-to-use/decentlab/dl-dlr2-003',
        'use-the-network/devices/ready-to-use/decentlab/dl-dlr2-004',
        'use-the-network/devices/ready-to-use/decentlab/dl-dlr2-005',
        'use-the-network/devices/ready-to-use/decentlab/dl-dlr2-006',
        'use-the-network/devices/ready-to-use/decentlab/dl-dlr2-008',
        'use-the-network/devices/ready-to-use/decentlab/dl-dlr2-010',
        'use-the-network/devices/ready-to-use/decentlab/dl-dlr2-012',
        'use-the-network/devices/ready-to-use/decentlab/dl-ds18',
        'use-the-network/devices/ready-to-use/decentlab/dl-dws',
        'use-the-network/devices/ready-to-use/decentlab/dl-itst',
        'use-the-network/devices/ready-to-use/decentlab/dl-kl66',
        'use-the-network/devices/ready-to-use/decentlab/dl-lid',
        'use-the-network/devices/ready-to-use/decentlab/dl-lp8p',
        'use-the-network/devices/ready-to-use/decentlab/dl-optod',
        'use-the-network/devices/ready-to-use/decentlab/dl-par',
        'use-the-network/devices/ready-to-use/decentlab/dl-pm',
        'use-the-network/devices/ready-to-use/decentlab/dl-pr21',
        'use-the-network/devices/ready-to-use/decentlab/dl-pr36',
        'use-the-network/devices/ready-to-use/decentlab/dl-pr36ctd',
        'use-the-network/devices/ready-to-use/decentlab/dl-pyr',
        'use-the-network/devices/ready-to-use/decentlab/dl-rhc',
        'use-the-network/devices/ready-to-use/decentlab/dl-sht35-001',
        'use-the-network/devices/ready-to-use/decentlab/dl-sht35-002',
        'use-the-network/devices/ready-to-use/decentlab/dl-smtp',
        'use-the-network/devices/ready-to-use/decentlab/dl-tbrg',
        'use-the-network/devices/ready-to-use/decentlab/dl-trs11',
        'use-the-network/devices/ready-to-use/decentlab/dl-trs12',
        'use-the-network/devices/ready-to-use/decentlab/dl-trs21',
        'use-the-network/devices/ready-to-use/decentlab/dl-wrm',
        'use-the-network/devices/ready-to-use/decentlab/dl-zn1',
        'use-the-network/devices/ready-to-use/decentlab/dl-zn2',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Develiot',
      items: [
        'use-the-network/devices/ready-to-use/develiot/rwmr',
        'use-the-network/devices/ready-to-use/develiot/uaqms',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Digtal Matter',
      items: [
        'use-the-network/devices/ready-to-use/digital-matter/oyster',
        'use-the-network/devices/ready-to-use/digital-matter/yabby-edge',
        'use-the-network/devices/ready-to-use/digital-matter/digital-matter-lorawan-gps',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Dragino',
      items: [
        'use-the-network/devices/ready-to-use/dragino/rs485-ln',
        'use-the-network/devices/ready-to-use/dragino/rs485-bl',
        'use-the-network/devices/ready-to-use/dragino/lsn50v2-s31',
        'use-the-network/devices/ready-to-use/dragino/lsn50v2-d20',
        'use-the-network/devices/ready-to-use/dragino/ldds20',
        'use-the-network/devices/ready-to-use/dragino/ldds75',
        'use-the-network/devices/ready-to-use/dragino/lbt1',
        'use-the-network/devices/ready-to-use/dragino/lse01',
        'use-the-network/devices/ready-to-use/dragino/lwl01',
        'use-the-network/devices/ready-to-use/dragino/lds01',
        'use-the-network/devices/ready-to-use/dragino/lds02',
        'use-the-network/devices/ready-to-use/dragino/lgt92',
        'use-the-network/devices/ready-to-use/dragino/lt22222-l',
        'use-the-network/devices/ready-to-use/dragino/lt33222-l',
        'use-the-network/devices/ready-to-use/dragino/lht65',
        'use-the-network/devices/ready-to-use/dragino/lsn50-v2',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Enthutech',
      items: [
        'use-the-network/devices/ready-to-use/enthutech/rs485-ln',
        'use-the-network/devices/ready-to-use/enthutech/rs485-bl',
        'use-the-network/devices/ready-to-use/enthutech/lsn50v2-s31',
        'use-the-network/devices/ready-to-use/enthutech/lsn50v2-d20',
        'use-the-network/devices/ready-to-use/enthutech/ldss20',
        'use-the-network/devices/ready-to-use/enthutech/ldds75',
        'use-the-network/devices/ready-to-use/enthutech/lbt1',
        'use-the-network/devices/ready-to-use/enthutech/lse01',
        'use-the-network/devices/ready-to-use/enthutech/lwl01',
        'use-the-network/devices/ready-to-use/enthutech/lds01',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'IMST',
      items: [
        'use-the-network/devices/ready-to-use/imst/range-extender',
        'use-the-network/devices/ready-to-use/imst/ioke868',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'IoTsens',
      items: [
        'use-the-network/devices/ready-to-use/iotsens/sound-device',
        'use-the-network/devices/ready-to-use/iotsens/airquality-device',
        'use-the-network/devices/ready-to-use/iotsens/lidar-device',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'izinto',
      items: ['use-the-network/devices/ready-to-use/izinto/izi-io-4840'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Laird',
      items: [
        'use-the-network/devices/ready-to-use/laird/rs1xx-temp-rh-sensor',
        'use-the-network/devices/ready-to-use/laird/rs1xx-ext-temp-1w-sensor',
        'use-the-network/devices/ready-to-use/laird/rs1xx-ext-multi-sensor',
        'use-the-network/devices/ready-to-use/laird/rs1xx-ext-temp-rtd-sensor',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'mcf88',
      items: [
        'use-the-network/devices/ready-to-use/mcf88/mcf-lw06davk',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lw06davpk',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lw12co2',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lw12met',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lw12plg',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lw12ter',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lw12terwp',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lw12terpm',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lw12voc',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lw13io',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lw13mio',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lwws00',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lwws01',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lwws02',
        'use-the-network/devices/ready-to-use/mcf88/mcf-lwws03',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'MClimate',
      items: [
        'use-the-network/devices/ready-to-use/mclimate/vicki',
        'use-the-network/devices/ready-to-use/mclimate/t-valve',
        'use-the-network/devices/ready-to-use/mclimate/flood-sensor',
        'use-the-network/devices/ready-to-use/mclimate/ht-sensor',
        'use-the-network/devices/ready-to-use/mclimate/aqi-sensor',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Milesight',
      items: [
        'use-the-network/devices/ready-to-use/milesight-iot/am107',
        'use-the-network/devices/ready-to-use/milesight-iot/em300-th',
        'use-the-network/devices/ready-to-use/milesight-iot/em500-co2',
        'use-the-network/devices/ready-to-use/milesight-iot/em500-udl',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Moko',
      items: [
        'use-the-network/devices/ready-to-use/moko/lw001-bg',
        'use-the-network/devices/ready-to-use/moko/lw003-b',
        'use-the-network/devices/ready-to-use/moko/lw004',
        'use-the-network/devices/ready-to-use/moko/lw005-mp',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Netvox',
      items: [
        'use-the-network/devices/ready-to-use/netvox/r311a',
        'use-the-network/devices/ready-to-use/netvox/r311b',
        'use-the-network/devices/ready-to-use/netvox/r311g',
        'use-the-network/devices/ready-to-use/netvox/r311w',
        'use-the-network/devices/ready-to-use/netvox/r312',
        'use-the-network/devices/ready-to-use/netvox/r312a',
        'use-the-network/devices/ready-to-use/netvox/r711',
        'use-the-network/devices/ready-to-use/netvox/r718a',
        'use-the-network/devices/ready-to-use/netvox/r718ab',
        'use-the-network/devices/ready-to-use/netvox/r718b',
        'use-the-network/devices/ready-to-use/netvox/r718ck',
        'use-the-network/devices/ready-to-use/netvox/r718ct',
        'use-the-network/devices/ready-to-use/netvox/r718e',
        'use-the-network/devices/ready-to-use/netvox/r718f',
        'use-the-network/devices/ready-to-use/netvox/r718n1',
        'use-the-network/devices/ready-to-use/netvox/r718n3',
        'use-the-network/devices/ready-to-use/netvox/r718t',
        'use-the-network/devices/ready-to-use/netvox/r720a',
        'use-the-network/devices/ready-to-use/netvox/r72615',
        'use-the-network/devices/ready-to-use/netvox/r72615a',
        'use-the-network/devices/ready-to-use/netvox/ra0715',
        'use-the-network/devices/ready-to-use/netvox/ra0715y',
        'use-the-network/devices/ready-to-use/netvox/rb02i',
        'use-the-network/devices/ready-to-use/netvox/rb11e',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Agriseen',
      items: [
        'use-the-network/devices/ready-to-use/agriseen/GA5067',
        'use-the-network/devices/ready-to-use/agriseen/JS0050',
        'use-the-network/devices/ready-to-use/agriseen/JS0130',
        'use-the-network/devices/ready-to-use/agriseen/JS0140',
      ],

      collapsed: true,
    },
    {
      type: 'category',
      label: 'Nwave',
      items: ['use-the-network/devices/ready-to-use/nwave/nps310sm'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Origo',
      items: [
        'use-the-network/devices/ready-to-use/origo/lorawan-watch',
        'use-the-network/devices/ready-to-use/origo/smart-badges',
      ],

      collapsed: true,
    },
    {
      type: 'category',
      label: 'RAKwireless',
      items: [
        'use-the-network/devices/ready-to-use/rakwireless/rak2171',
        'use-the-network/devices/ready-to-use/rakwireless/rak7200',
        'use-the-network/devices/ready-to-use/rakwireless/rak7201',
        'use-the-network/devices/ready-to-use/rakwireless/rak7204',
        'use-the-network/devices/ready-to-use/rakwireless/rak7431',
        'use-the-network/devices/ready-to-use/rakwireless/rak10700',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Seeed Studio',
      items: [
        'use-the-network/devices/ready-to-use/seeed-studio/sensecap-s2100-data-logger',
        'use-the-network/devices/ready-to-use/seeed-studio/sensecap-s2101-tem-humid',
        'use-the-network/devices/ready-to-use/seeed-studio/sensecap-s2102-light',
        'use-the-network/devices/ready-to-use/seeed-studio/sensecap-s2103-co2-tem-humid',
        'use-the-network/devices/ready-to-use/seeed-studio/sensecap-s2104-soil-mois-tem',
        'use-the-network/devices/ready-to-use/seeed-studio/sensecap-s2105-soil-mois-tem-ec',
        'use-the-network/devices/ready-to-use/seeed-studio/sensecap-soil-th',
        'use-the-network/devices/ready-to-use/seeed-studio/sensecap-air-th',
        'use-the-network/devices/ready-to-use/seeed-studio/sensecap-light',
        'use-the-network/devices/ready-to-use/seeed-studio/sensecap-co2',
        'use-the-network/devices/ready-to-use/seeed-studio/sensecap-pressure',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Sensedge',
      items: [
        'use-the-network/devices/ready-to-use/sensedge/senstick-pro',
        'use-the-network/devices/ready-to-use/sensedge/senstick-pure',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Tektelic',
      items: [
        'use-the-network/devices/ready-to-use/tektelic/t000489x-smart-room-base',
        'use-the-network/devices/ready-to-use/tektelic/t00048xx-smart-room-pir',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Tekzitel',
      items: ['use-the-network/devices/ready-to-use/tekzitel/tekzipark'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'The Things Products',
      items: [
        'use-the-network/devices/ready-to-use/the-things-products/the-things-node',
        'use-the-network/devices/ready-to-use/the-things-products/the-things-uno',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Victor',
      items: ['use-the-network/devices/ready-to-use/victor/victor-trap-v4xx'],
      collapsed: true,
    },
  ],

  iot_device_development: [
    {
      type: 'link',
      label: '<- Devices',
      href: '/use-the-network/devices',
    },
    'use-the-network/devices/development/development',
    {
      type: 'category',
      label: 'Adafruit',
      items: [
        'use-the-network/devices/development/adafruit/adafruit-feather-m0-rfm95/adafruit-feather-m0-rfm95',
        'use-the-network/devices/development/adafruit/adafruit-feather-m0-rfm95/arduino',
        'use-the-network/devices/development/adafruit/adafruit-feather-m0-rfm95/adafruitio',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Arduino',
      items: [
        'use-the-network/devices/development/arduino/mkr-wan-1310',
        {
          type: 'category',
          label: 'Portenta Vision Shield',
          link: {
            type: 'doc',
            id: 'use-the-network/devices/development/arduino/lora-vision-shield/lora-vision-shield',
          },
          items: ['use-the-network/devices/development/arduino/lora-vision-shield/arduino'],
          collapsed: true,
        },
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Embit',
      items: [
        'use-the-network/devices/development/embit/emb-lr1280s',
        'use-the-network/devices/development/embit/emb-lrwl55',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Heltec',
      items: [
        'use-the-network/devices/development/heltec/cubecell-gps-6502',
        {
          type: 'category',
          label: 'HTCC-AB01',
          link: {
            type: 'doc',
            id: 'use-the-network/devices/development/heltec/cubecell-dev-board/cubecell-dev-board',
          },
          items: [
            'use-the-network/devices/development/heltec/cubecell-dev-board/arduino',
            'use-the-network/devices/development/heltec/cubecell-dev-board/platformio',
          ],
          collapsed: true,
        },
        'use-the-network/devices/development/heltec/cubecell-dev-board-plus',
        'use-the-network/devices/development/heltec/cubecell-1-2-aa-node',
        'use-the-network/devices/development/heltec/cubecell-capsule-sensor',
        'use-the-network/devices/development/heltec/cubecell-solar-sensor',
        'use-the-network/devices/development/heltec/cubecell-module',
        'use-the-network/devices/development/heltec/cubecell-module-plus',
        {
          type: 'category',
          label: 'Wifi Lora 32 V2',
          link: {
            type: 'doc',
            id: 'use-the-network/devices/development/heltec/wifi-lora-32-v2/wifi-lora-32-v2',
          },
          items: ['use-the-network/devices/development/heltec/wifi-lora-32-v2/arduino'],
          collapsed: true,
        },
        'use-the-network/devices/development/heltec/wireless-stick',
        'use-the-network/devices/development/heltec/wireless-stick-lite',
        'use-the-network/devices/development/heltec/wireless-shell',
        'use-the-network/devices/development/heltec/lora-kit-151',
        'use-the-network/devices/development/heltec/lora-node-151',
        'use-the-network/devices/development/heltec/turtle-board',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'MCCI',
      items: [
        'use-the-network/devices/development/mcci/catena4430',
        'use-the-network/devices/development/mcci/catena4450',
        'use-the-network/devices/development/mcci/catena4460',
        'use-the-network/devices/development/mcci/catena4470',
        'use-the-network/devices/development/mcci/catena4610',
        'use-the-network/devices/development/mcci/catena4612',
        'use-the-network/devices/development/mcci/catena4618',
        'use-the-network/devices/development/mcci/catena4618m201',
        'use-the-network/devices/development/mcci/catena4801',
        'use-the-network/devices/development/mcci/catena4802',
        'use-the-network/devices/development/mcci/model4811',
        'use-the-network/devices/development/mcci/model4821',
        'use-the-network/devices/development/mcci/model4822',
        'use-the-network/devices/development/mcci/model4823',
        'use-the-network/devices/development/mcci/model4831',
        'use-the-network/devices/development/mcci/model4832',
        'use-the-network/devices/development/mcci/model4841',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Midatronics',
      items: [
        'use-the-network/devices/development/midatronics/windy-module',
        'use-the-network/devices/development/midatronics/windy-mkr',
        'use-the-network/devices/development/midatronics/sharky-module',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Multi-Tech',
      items: ['use-the-network/devices/development/multi-tech/multi-tech-xdot'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'OpenSource Initiative',
      items: ['use-the-network/devices/development/opensourceinitiative/paxcounter'],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'RAK Wireless',
      items: [
        {
          type: 'category',
          label: 'Wisblock Starter Kit Rak4631',
          link: {
            type: 'doc',
            id: 'use-the-network/devices/development/rakwireless/wisblock-4631/wisblock-4631',
          },
          items: [
            'use-the-network/devices/development/rakwireless/wisblock-4631/arduino',
            'use-the-network/devices/development/rakwireless/wisblock-4631/platformio',
          ],
          collapsed: true,
        },
        'use-the-network/devices/development/rakwireless/rak7431',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Seeed Studio',
      items: [
        'use-the-network/devices/development/seeed-studio/loramodule-e5',
        'use-the-network/devices/development/seeed-studio/loramodule-e5-devkit',
        'use-the-network/devices/development/seeed-studio/loramodule-e5-mini',
        'use-the-network/devices/development/seeed-studio/loramodule-e5-grove',
        'use-the-network/devices/development/seeed-studio/seeed-studio-lorawan-dev-kit',
      ],

      collapsed: true,
    },
    {
      type: 'category',
      label: 'Sparkfun',
      items: [
        'use-the-network/devices/development/sparkfun/pro-rf/pro-rf',
        'use-the-network/devices/development/sparkfun/pro-rf/arduino',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'STMicroelectronics',
      items: [
        {
          type: 'category',
          label: 'ST B-L072Z-LRWAN1',
          link: {
            type: 'doc',
            id: 'use-the-network/devices/development/stmicroelectronics/st-b-l072z-lrwan1/st-b-l072z-lrwan1',
          },
          items: [
            'use-the-network/devices/development/stmicroelectronics/st-b-l072z-lrwan1/arduino',
            'use-the-network/devices/development/stmicroelectronics/st-b-l072z-lrwan1/platformio',
          ],
          collapsed: true,
        },
        'use-the-network/devices/development/stmicroelectronics/nucleo-wl55jc1',
        'use-the-network/devices/development/stmicroelectronics/nucleo-wl55jc2',
      ],
      collapsed: true,
    },
  ],

  migration: [
    'solana/migration-overview',
    'solana/migration-faq',
    'solana/migration/hotspot-operator',
    'solana/migration/validator-operator',
    {
      type: 'category',
      label: 'Hotspot Maker',
      items: ['solana/migration/maker', 'solana/migration/maker-hotspot-software'],
    },
    'solana/migration/exchange',
    'solana/migration/network-user',
    'solana/migration/console-operator',
    'solana/migration/application-builder',
    'solana/migration/governance',
    'solana/migration/blockchain-node',
    'solana/migration/blockchain-api',
    'solana/migration/blockchain-etl',
    'solana/migration/wallet-user',
    'solana/migration/ledger',
    'solana/migration/hst',
  ],
}
